### PR TITLE
Command 'switch'

### PR DESCRIPTION
**Pull request by termanator1128**
Ability to switch between characters without having to log out

### CODE REVIEW

**Comment by onno204** [comment]
I don't think this will work due to how ESX loads characters

**Comment by lenzh** [comment]
i can confirm that this method is not working it changes everything except skin

**Comment by termanator1128** [comment]
@onno204 @lenzh Confirmed that it is working with no issues. I wouldn't make it and a PR without testing.

**Comment by lenzh** [comment]
i installed it and did the command.. yes it goes to the login screen but if you change character skin and playerdata isnt changing

**Pull request closed without merging**
